version: 2.1
# example https://stackoverflow.com/a/65001814/720276

orbs:
  codecov: codecov/codecov@1.0.2
  workflows:
    upload-to-codecov:
      jobs:
      - checkout
      - codecov/upload  

jobs:
  run_jest_tests:
    docker:
      - image: cimg/node:15.1
      - image: circleci/mongo:4.4.1
        environment:
          DATABASE_URL: mongodb://localhost/?

    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Waiting for MongoDB to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MongoDB && exit 1
      - run:
          name: Run Tests
          command: npm run circle
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  orb-free-workflow:
    jobs:
      - run_jest_tests
